{"name": "test_answer1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "self = <Pytest.test_shili.TestFunc object at 0x000002190DE02580>\n\n    @pytest.mark.fail\n    @allure.story('测试用例1')\n    def test_answer1(self):\n        print('test_answer1')\n>       assert func(3) == 5\nE       assert 4 == 5\nE        +  where 4 = func(3)\n\ntest_shili.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "46f62955-6311-4110-8b16-657c01ac150d-attachment.txt", "type": "text/plain"}], "start": 1642067392331, "stop": 1642067392331, "uuid": "ed2409e5-bc9c-4746-a91f-dc39ae4e06dc", "historyId": "4fbbb282760c3edd2124dece81c6cef5", "testCaseId": "c636ebfb1ab8cacacb8c6df4270b428f", "fullName": "test_shili.TestFunc#test_answer1", "labels": [{"name": "feature", "value": "*****测试类*****"}, {"name": "story", "value": "测试用例1"}, {"name": "tag", "value": "fail"}, {"name": "suite", "value": "test_shili"}, {"name": "subSuite", "value": "TestFunc"}, {"name": "host", "value": "DESKTOP-V45JC51"}, {"name": "thread", "value": "44332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_shili"}]}